# Generated by Django 3.2.6 on 2021-10-01 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0006_auto_20211001_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='avg_rating',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='number_rating',
        ),
    ]
