# Generated by Django 3.2.6 on 2021-10-01 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0008_auto_20211001_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='avg_rating',
            new_name='avg_of_rating',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='number_rating',
            new_name='number_of_rating',
        ),
    ]
